# Generated by Django 4.2.27 on 2025-12-04 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['unit__code', 'semester', 'session_number', 'date', 'start_time']},
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('unit', 'semester', 'session_number'), name='unique_unit_semester_session'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('unit', 'semester', 'date', 'start_time'), name='unique_unit_semester_datetime'),
        ),
    ]
