# Generated by Django 4.2.27 on 2025-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='class_year',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4'), ('Year 5', 'Year 5')], default='Year 1', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='lecturer_name',
            field=models.CharField(blank=True, help_text="Lecturer's name as entered for this session", max_length=100),
        ),
    ]
