# Generated by Django 4.2.27 on 2026-05-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancesession_class_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='firebase_doc_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='synced_to_firebase',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='synced_to_portal',
        ),
    ]
